language: node_js
sudo: false
cache: yarn
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6

branches:
    only:
        - main

install:
  - cd backend && yarn install

script:
  - cd backend && yarn test && yarn test:e2e
