version: "3.4"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - backend
    env_file:
      - .env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3014:3014"
    networks:
      - backend
    restart: on-failure
    depends_on:
      - mariadb
    links:
      - mariadb:3306
    env_file:
      - .env
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: takemehome
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3316:3306"
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

networks:
  backend:
    driver: bridge
