name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test backend
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd backend && yarn
    - run: cd backend && yarn test
    - run: cd backend && yarn test:e2e
    - run: cd frontend && yarn
    - run: cd frontend && yarn test:headless
    - run: cd frontend && yarn e2e
